# Generated by Django 2.1.4 on 2019-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=400)),
                ('DueDate', models.DateField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
